name: hub-00
executor: http://executor:7166/
judge: http://judge:7167/
reporter: http://reporter:7168/

idTracker: lastid

server:
  applicationConnectors:
  - type: http
    port: 7165
  adminConnectors:
  - type: http
    port: 7175
